### ISSUE TITLE
2.0.4 broken while hovering over

### ISSUE THREAD

**Issue by tkozyrski** [akempes/angular-rateit#8]
TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at r.a.onEnter (/dist/ng-rateit.min.js:1:1684)
    at fn (eval at <anonymous> (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:213:110), <anonymous>:4:316)
    at e (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:254:74)
    at r.$eval (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:133:313)
    at r.$apply (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:134:17)
    at HTMLDivElement.<anonymous> (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:254:126)
    at HTMLDivElement.n.event.special.(anonymous function).handle (http://code.jquery.com/jquery-2.1.4.min.js:3:10169)
    at HTMLDivElement.n.event.dispatch (http://code.jquery.com/jquery-2.1.4.min.js:3:6466)
    at HTMLDivElement.r.handle (http://code.jquery.com/jquery-2.1.4.min.js:3:3241)

**Comment by akempes** [comment]
Hi,

I found some time to have a look at this issue. I was unable to reproduce this error but @inabhi9 fixed the problem already. I've just issued a new release. Can you please check if it's working now??

Thanks!

**Comment by inabhi9** [comment]
@akempes thanks! I was not sure if it's right way to fix it, so hesitated to send PR

**Comment by tkozyrski** [comment]
It seems ok now, thanks.
